apiVersion: v1
kind: Secret
metadata:
  name: database
type: Opaque
stringData:
  AUTH: "AUTH_MONGO_URI"
  SANDBOX: "SANDBOX_MONGO_URI"
  AI: "AI_MONGO_URI"
  REDIS_URL: "redis://default"

---
apiVersion: v1
kind: Secret
metadata:
  name: google
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID"
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET"
  GOOGLE_CALLBACK_URL: "GOOGLE_CALLBACK_URL"

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt
type: Opaque
stringData:
  JWT_SECRET: "JWT_SECRET"
